# Generated by Django 4.2.7 on 2025-12-20 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100, verbose_name='动作名称')),
                ('reps', models.IntegerField(verbose_name='完成次数')),
                ('set_index', models.IntegerField(verbose_name='第几组')),
                ('is_completed', models.BooleanField(default=True, verbose_name='是否成功')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='完成时间')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='api.workouthistory', verbose_name='所属训练')),
            ],
            options={
                'verbose_name': '训练组记录',
                'verbose_name_plural': '训练组记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
