# Generated by Django 4.2.7 on 2025-12-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_workoutset"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_title", models.CharField(max_length=200, verbose_name="关联计划")),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                ("duration", models.IntegerField(default=0, verbose_name="训练时长(秒)")),
                ("data_snapshot", models.JSONField(verbose_name="完成情况快照")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "已完成"),
                            ("interrupted", "已中断"),
                            ("failed", "失败"),
                        ],
                        default="interrupted",
                        max_length=20,
                    ),
                ),
                (
                    "ai_score",
                    models.FloatField(blank=True, null=True, verbose_name="AI评分"),
                ),
                (
                    "ai_feedback",
                    models.TextField(blank=True, null=True, verbose_name="AI建议"),
                ),
            ],
            options={
                "verbose_name": "训练记录",
                "verbose_name_plural": "训练记录",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="计划名称")),
                ("data", models.JSONField(verbose_name="训练配置")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认计划"),
                ),
            ],
            options={
                "verbose_name": "训练计划",
                "verbose_name_plural": "训练计划",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="workoutset",
            name="history",
        ),
        migrations.DeleteModel(
            name="WorkoutHistory",
        ),
        migrations.DeleteModel(
            name="WorkoutSet",
        ),
    ]
