# Generated by Django 4.2.7 on 2025-12-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_workoutlog_workoutplan_remove_workoutset_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutlog",
            name="set_feedback",
            field=models.JSONField(blank=True, null=True, verbose_name="每组AI反馈"),
        ),
    ]
