# Generated by Django 4.2.7 on 2025-12-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_workoutlog_set_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutlog",
            name="action_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="动作名称"
            ),
        ),
        migrations.AddField(
            model_name="workoutlog",
            name="reps_count",
            field=models.IntegerField(default=0, verbose_name="完成次数"),
        ),
        migrations.AddField(
            model_name="workoutlog",
            name="set_index",
            field=models.IntegerField(blank=True, null=True, verbose_name="组数索引"),
        ),
    ]
