# Generated by Django 4.2.7 on 2025-12-20 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_workoutlog_action_name_workoutlog_reps_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workoutplan",
            name="data",
        ),
        migrations.CreateModel(
            name="WorkoutExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="动作名称")),
                ("total_sets", models.IntegerField(default=3, verbose_name="总组数")),
                ("reps_per_set", models.IntegerField(default=12, verbose_name="每组次数")),
                (
                    "current_sets",
                    models.IntegerField(default=0, verbose_name="当前已完成组数"),
                ),
                ("tips", models.TextField(blank=True, null=True, verbose_name="动作要领")),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="api.workoutplan",
                        verbose_name="所属计划",
                    ),
                ),
            ],
            options={
                "verbose_name": "训练动作",
                "verbose_name_plural": "训练动作",
                "ordering": ["order", "id"],
            },
        ),
    ]
