# Generated by Django 4.2.7 on 2025-12-20 08:44

from django.db import migrations, models


def migrate_data_from_snapshot(apps, schema_editor):
    """
    从 data_snapshot 中提取数据到新字段
    """
    WorkoutLog = apps.get_model('api', 'WorkoutLog')
    
    for log in WorkoutLog.objects.all():
        if log.data_snapshot:
            snapshot = log.data_snapshot
            
            # 提取 exercise_id
            if 'exercise_id' in snapshot:
                log.exercise_id = snapshot['exercise_id']
            elif 'id' in snapshot:
                log.exercise_id = snapshot['id']
                
            # 提取 target_reps
            if 'target_reps' in snapshot:
                log.target_reps = snapshot['target_reps']
            elif 'reps_per_set' in snapshot:
                log.target_reps = snapshot['reps_per_set']
                
            # 提取 target_sets
            if 'target_sets' in snapshot:
                log.target_sets = snapshot['target_sets']
            elif 'total_sets' in snapshot:
                log.target_sets = snapshot['total_sets']
            
            log.save(update_fields=['exercise_id', 'target_reps', 'target_sets'])


def reverse_migrate(apps, schema_editor):
    """
    反向迁移：将数据移回 data_snapshot
    """
    WorkoutLog = apps.get_model('api', 'WorkoutLog')
    
    for log in WorkoutLog.objects.all():
        if log.exercise_id or log.target_reps or log.target_sets:
            snapshot = log.data_snapshot or {}
            if log.exercise_id:
                snapshot['exercise_id'] = log.exercise_id
            if log.target_reps:
                snapshot['target_reps'] = log.target_reps
            if log.target_sets:
                snapshot['target_sets'] = log.target_sets
            log.data_snapshot = snapshot
            log.save(update_fields=['data_snapshot'])


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_cleanup_data_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutlog",
            name="exercise_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="动作ID"),
        ),
        migrations.AddField(
            model_name="workoutlog",
            name="target_reps",
            field=models.IntegerField(blank=True, null=True, verbose_name="目标次数"),
        ),
        migrations.AddField(
            model_name="workoutlog",
            name="target_sets",
            field=models.IntegerField(blank=True, null=True, verbose_name="目标组数"),
        ),
        migrations.AlterField(
            model_name="workoutlog",
            name="data_snapshot",
            field=models.JSONField(blank=True, null=True, verbose_name="完成情况快照"),
        ),
        migrations.RunPython(migrate_data_from_snapshot, reverse_migrate),
    ]
