# Generated by Django 4.2.7 on 2025-12-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_workoutlog_exercise_id_workoutlog_target_reps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutexercise",
            name="end_time",
            field=models.CharField(default="00:00", max_length=10, verbose_name="结束时间"),
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="seconds",
            field=models.IntegerField(default=0, verbose_name="开始秒数"),
        ),
        migrations.AddField(
            model_name="workoutexercise",
            name="start_time",
            field=models.CharField(default="00:00", max_length=10, verbose_name="开始时间"),
        ),
    ]
