# Generated by Django 4.2.7 on 2025-12-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_workoutexercise_end_time_workoutexercise_seconds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutexercise",
            name="gif_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="动作演示GIF"
            ),
        ),
    ]
