# Generated by Django 4.2.7 on 2025-12-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_workoutexercise_gif_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutexercise",
            name="category",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="动作类别"
            ),
        ),
    ]
