# Generated by Django 4.2.7 on 2025-12-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_workoutexercise_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutexercise",
            name="muscle_group",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="训练部位"
            ),
        ),
    ]
